# ============================================
# 3. LITELLM CONFIGMAP
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    model_list:
      - model_name: gemini-pro
        litellm_params:
          model: vertex_ai/gemini-pro
          vertex_project: "pdlgcpcloud"
          vertex_location: "us-central1"
      
      - model_name: gemini-pro-vision
        litellm_params:
          model: vertex_ai/gemini-pro-vision
          vertex_project: "pdlgcpcloud"
          vertex_location: "us-central1"
      
      - model_name: gemini-flash
        litellm_params:
          model: vertex_ai/gemini-2.5-flash-lite
          vertex_project: "pdlgcpcloud"
          vertex_location: "us-central1"
    
    general_settings:
      # Temporarily disable master key for testing
      # master_key: "sk-1234"
      database_url: "postgresql://litellm:password@postgres-service.litellm.svc.cluster.local:5432/litellm"
      ui_username: "admin"
      ui_password: "admin123" 
    
    litellm_settings:
      drop_params: true
      set_verbose: true
      success_callback: ["langfuse"]
      num_retries: 3
      request_timeout: 600
      fallbacks: [{"gemini-pro": ["gemini-flash"]}]
