# ============================================
# 1. NAMESPACE CREATION
# ============================================
apiVersion: v1
kind: Namespace
metadata:
  name: litellm
  labels:
    name: litellm
    app: litellm-gateway
