# ============================================
# 5. LITELLM SERVICE (LoadBalancer)
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: litellm-service
  namespace: litellm
spec:
  type: LoadBalancer
  selector:
    app: litellm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
    name: http
  sessionAffinity: ClientIP