apiVersion: v2
name: litellm-gateway
description: A Helm chart for LiteLLM Gateway with Vertex AI integration
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - litellm
  - ai
  - gateway
  - vertex-ai
  - gcp
home: https://github.com/BerriAI/litellm
sources:
  - https://github.com/BerriAI/litellm
maintainers:
  - name: Awadhesh Pandey
    email: dotnetdev12@paisalo.in
